module.exports = {
  PROCESS_BEFORE_EXIT: 'PROCESS_BEFORE_EXIT',
  PROCESS_EXIT: 'PROCESS_EXIT',
  UNCAUGHT_EXECPTION: 'UNCAUGHT_EXECPTION',
  DATABASE_DISCONNECTED: 'DATABASE_DISCONNECTED',
  REPORT_ERROR: 'REPORT_ERROR',
};
